# Site settings
title: Thailandia
client:
  name: Qatar Airways
  link: https://www.qatarairways.com/it-it/offers/voli-per-thailandia.html?CID=BAIT862440
core-se-link: https://it.secretescapes.com/offerte-in-corso
description: >
  Sei già stato in Thailandia? Che la tua risposta sia affermativa o negativa, poco importa. Questo paese, da nord a sud, ha tantissimo da offrirti: dalle colline e le montagne ricoperte di natura rigogliosa, alle spiagge bianchissime, passando per i templi che raccontano storie antiche e suggestive, avrai tantissimo da scoprire ed esplorare, sempre accompagnato da un’atmosfera rilassata che contraddistingue la cultura thai.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/it/thailandia" # the subpath of your site, e.g. /blog/
img:     "/it/thailandia/_assets/img"
css:     "/it/thailandia/_assets/css"
js:      "/it/thailandia/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed